bootstrap/ (запуск с бд, сервера итп)
calculators/ (вычисление чего-либо)
components/ (компоненты фронта)
controllers/ (обработка запросов бекенда)
interfaces/ (интерфейсы для всех типов модулей)
layouts/ (блоки фронта)
middlewares/ (мидлверы и фронта и бека)
models/ (модели)
pages/ (страницы фронта)
config.ts (общий конфиг)
index.ts (точка входа)
router.ts (обработка урлов)
